import { cx } from "@utils/tools";
import Head from "next/head";

export const DetailsScreen: IComponent = ({}) => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="details">Hello from details</main>
    </div>
  );
};
