import { DarkmodeAtom, ProjectInfoListAtom } from "@atoms/app";
import { TemplateComponent } from "@components/_template";
import { Banner } from "@components/Banner";
import { ProjectCard } from "@components/ProjectCard/indext";
import { TEAM_NAME } from "@env";
import { cx } from "@utils/tools";
import Head from "next/head";
import { useRouter } from "next/router";
import useTranslation from "next-translate/useTranslation";
import { useRecoilState } from "recoil";

import styles from "./styles.module.scss";

export const AppScreen: IComponent = ({}) => {
  const { t, lang } = useTranslation("common");
  const [darkMode, setDarkMode] = useRecoilState(DarkmodeAtom);
  const [projectInfoList] = useRecoilState(ProjectInfoListAtom);
  const router = useRouter();

  return (
    <div className={cx("dark:text-white")}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner></Banner>
      <main className={styles.main}>
        <h1 className="font-semibold lg:text-4xl">
          {"Our works".toUpperCase()}
        </h1>

        <div className={styles.grid}>
          {projectInfoList.map((projectInfo, idx) => (
            <ProjectCard key={idx} projectInfo={projectInfo}></ProjectCard>
          ))}
        </div>
      </main>
    </div>
  );
};
