import { DarkmodeAtom, ProjectInfoListAtom } from "@atoms/app";
import { TemplateComponent } from "@components/_template";
import { TEAM_NAME } from "@env";
import { cx } from "@utils/tools";
import Head from "next/head";
import { useRouter } from "next/router";
import setLanguage from "next-translate/setLanguage";
import useTranslation from "next-translate/useTranslation";
import { useRecoilState } from "recoil";

import styles from "./styles.module.scss";

export const AppScreen: IComponent = ({}) => {
  const { t, lang } = useTranslation("common");
  const [darkMode, setDarkMode] = useRecoilState(DarkmodeAtom);
  const [projectInfoList] = useRecoilState(ProjectInfoListAtom);
  const router = useRouter();

  return (
    <div className={cx(styles.container, "dark:text-white")}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="font-semibold lg:text-4xl">
          {"Our works".toUpperCase()}
        </h1>

        <div className={styles.grid}>
          {projectInfoList.map((projectInfo, idx) => (
            <a href="https://nextjs.org/docs" className={styles.card} key={idx}>
              <h2 className="font-semibold lg:text-xl text-base">
                {projectInfo.name}
              </h2>
              <p className="!text-xs whitespace-pre-line">
                {projectInfo.description}
              </p>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
};
