import { DarkmodeAtom } from "@atoms/app";
import { ContentComponent } from "@components/Content";
import { WidgetComponent } from "@components/Widget";
import { Projects } from "@configs/detail";
import { cx } from "@utils/tools";
import Head from "next/head";
import { useRecoilState } from "recoil";

export const DetailsScreen: IComponent = ({}) => {
  const [darkMode, setDarkMode] = useRecoilState(DarkmodeAtom);

  const projectPrefix = window.location.pathname.split("/").pop();
  const projectDetail = Projects[projectPrefix!];

  /**
   * Fallback to warning if project not found
   */
  if (!projectDetail) {
    return (
      <div
        className="w-full flex justify-center items-center bg-white dark:bg-default"
        style={{ height: "80vh" }}
      >
        <h1 className="text-2xl text-black dark:text-white opacity-80">
          THIS PROJECT IS NOT <span className="font-bold">AVAILABLE</span>
        </h1>
      </div>
    );
  }

  const { data } = projectDetail;

  const content = data.content;
  const widget = data.widget_detail_1;
  const widget2 = data.widget_detail_2;

  return (
    <div className={cx("dark:text-white")}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="details min-h-screen ">
        <div className="bg-inherit banner py-24 xl:py-48">
          <div className="flex items-center justify-center ">
            <h1 className={"text-3xl xl:text-6xl font-bold text-inherit"}>
              OUR WORKS
            </h1>
          </div>
        </div>

        <div className="container mx-auto px-1 py-10 xl:py-40">
          <div className="grid grid-rows-3 xl:grid-rows-none xl:grid-cols-3 gap-10">
            <div className="row-span-2 xl:col-span-2 flex flex-col p-2">
              <ContentComponent {...content} />
            </div>
            <div className="flex flex-col justify-between  xl:flex xl:flex-col p-2">
              <WidgetComponent {...widget} />
              <WidgetComponent {...widget2} />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};
