name: Linting
on: [push]
jobs:
  linting:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: bahmutov/npm-install@v1

      - name: Run Eslint Checking
        run: yarn lint
