name: Linting
on: [push]
jobs:
  linting:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn & Eslint
        run: npm install -g yarn

      - uses: bahmutov/npm-install@v1

      - name: Run Eslint Checking
        run: yarn lint
